import Mathlib.Analysis.Normed.Module.Basic
import Mathlib.Dynamics.Flow
import Mathlib.Topology.Algebra.Ring.Real
import HeytingLean.MirandaDynamics.Fluids.ContactLinear

/-!
# MirandaDynamics.Fluids: a linear “Reeb flow” (constant vector field)

This file complements `Fluids.ContactLinear` by packaging the distinguished Reeb-style vector `R`
as a global `Flow ℝ V` via translations `x ↦ x + t • R`.

This is **not** a contact-geometry formalization; it is a small, mechanically checkable bridge
that can feed the existing `TKFT.reachingRelOfFlow` semantics.
-/

namespace HeytingLean
namespace MirandaDynamics
namespace Fluids

universe u

namespace ContactLinear

variable {V : Type u} [NormedAddCommGroup V] [NormedSpace ℝ V]

/-- The constant-velocity flow generated by the Reeb-style vector `R` in a `ContactLinear` package. -/
def reebFlow (C : ContactLinear (V := V)) : Flow ℝ V where
  toFun t x := x + t • C.R
  cont' := by
    -- continuity of `(t, x) ↦ x + t • R`
    simpa [Function.uncurry] using (continuous_snd.add (continuous_fst.smul continuous_const))
  map_add' := by
    intro t₁ t₂ x
    -- `x + (t₁ + t₂)•R = (x + t₂•R) + t₁•R`
    simp [add_smul, add_left_comm, add_comm]
  map_zero' := by
    intro x
    simp

@[simp] theorem reebFlow_apply (C : ContactLinear (V := V)) (t : ℝ) (x : V) :
    C.reebFlow t x = x + t • C.R :=
  rfl

end ContactLinear

end Fluids
end MirandaDynamics
end HeytingLean
